server {
    listen 80;
    listen [::]:80;
    server_name djelong.com www.djelong.com;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/djelong-next/releases/current;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name djelong.com www.djelong.com;

    root /var/www/djelong-next/releases/current;
    index index.html;

    ssl_certificate /etc/nginx/ssl/djelong.com.fullchain.cer;
    ssl_certificate_key /etc/nginx/ssl/djelong.com.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
